sonar.projectKey=ai-geologist
sonar.projectName=AI-Geologist
sonar.projectVersion=1.0

# Φάκελοι που θα ελέγξει (ελέγχουμε backend και frontend, αγνοούμε ρυθμίσεις)
sonar.sources=backend,frontend
sonar.python.version=3.10
sonar.exclusions=backend/model_files/**, **/*.joblib, **/*.ipynb